import '../assets/sass/app.scss';
import 'flatpickr/dist/flatpickr.min.css';
import 'dropzone/dist/min/dropzone.min.css';
import "./elm.js";
import "../webcomponents/DropzoneUpload/DropzoneUpload.js";
import "../webcomponents/Flatpickr/Flatpickr.js";
import "../webcomponents/GoogleMap/GoogleMap.js";
import "animate.css";
import "spinkit/css/spinkit.css";
